const services = [
  { no: "01", title: "Business websites", text: "Fast, responsive websites that make your business look credible and turn visitors into enquiries." },
  { no: "02", title: "E-commerce builds", text: "Product-focused storefronts with clear navigation, smooth checkout flows, and practical admin experiences." },
  { no: "03", title: "React & MERN apps", text: "Custom dashboards and full-stack web applications built with maintainable, production-minded code." },
  { no: "04", title: "Frontend improvements", text: "Responsive fixes, UI polishing, performance work, and converting designs into clean interfaces." },
];
const projects = [
  { index: "01", name: "Shoes House", type: "E-commerce web application", desc: "A focused shopping experience designed around clear product discovery and a smooth storefront journey.", stack: ["JavaScript", "E-commerce", "Responsive UI"], href: "https://github.com/CodedPraveen/shoes-house", tone: "blue" },
  { index: "02", name: "Get Me A Chai", type: "Creator crowdfunding platform", desc: "A Patreon-style platform with Razorpay payments and GitHub OAuth for creators to receive support.", stack: ["React", "Node.js", "MongoDB", "Razorpay"], href: "https://get-me-a-chai-inky.vercel.app/", tone: "lime" },
  { index: "03", name: "Pass OP", type: "Secure password manager", desc: "A clean full-stack interface for storing and managing credentials with a MongoDB-backed workflow.", stack: ["React", "Express", "MongoDB"], href: "https://pass-op-mongo-psi.vercel.app/", tone: "peach" },
];

export default function Home() {
  return <main>
    <nav className="nav shell" aria-label="Primary navigation"><a className="brand" href="#top" aria-label="CodedPraveen home"><span>&lt;</span>codedpraveen<span>/&gt;</span></a><div className="navLinks"><a href="#services">Services</a><a href="#work">Work</a><a href="#about">About</a></div><a className="navCta" href="#contact">Let&apos;s talk <span>↗</span></a></nav>
    <section className="hero shell" id="top"><div className="availability"><i /> Available for freelance projects</div><h1>Web experiences<br />built to <em>work.</em></h1><div className="heroBottom"><p>I&apos;m Praveen, a full-stack developer from Jodhpur. I help businesses and founders turn ideas into fast, thoughtful, real-world web products.</p><div className="heroActions"><a className="button dark" href="#work">View selected work <span>↓</span></a><a className="textLink" href="#contact">Start a project <span>↗</span></a></div></div><div className="heroMeta"><span>Based in Jodhpur, India</span><span>React · Next.js · MERN</span><span>Scroll to explore ↓</span></div></section>
    <section className="ticker" aria-label="Expertise"><div>Web development <b>✦</b> Responsive design <b>✦</b> E-commerce <b>✦</b> React applications <b>✦</b> API integration <b>✦</b> Web development <b>✦</b></div></section>
    <section className="section shell" id="services"><div className="sectionHead"><p className="eyebrow">What I can help with</p><h2>From a rough idea to a<br /><em>working product.</em></h2></div><div className="serviceGrid">{services.map((s) => <article className="service" key={s.no}><span>{s.no}</span><div className="serviceIcon" aria-hidden="true">{s.no === "01" ? "◰" : s.no === "02" ? "▦" : s.no === "03" ? "⌁" : "✦"}</div><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></section>
    <section className="workSection" id="work"><div className="shell"><div className="sectionHead workHead"><p className="eyebrow">Selected work</p><h2>Projects built by<br /><em>doing the work.</em></h2></div><div className="projects">{projects.map((p) => <a className={`project ${p.tone}`} href={p.href} target="_blank" rel="noreferrer" key={p.name}><div className="projectNum">{p.index}</div><div className="projectVisual"><div className="browser"><div className="browserTop"><i/><i/><i/></div><div className="mock"><span>{p.name}</span><div/><div/><button>Explore</button></div></div></div><div className="projectCopy"><p>{p.type}</p><h3>{p.name}</h3><div className="tags">{p.stack.map(t => <span key={t}>{t}</span>)}</div><p className="desc">{p.desc}</p></div><div className="arrow">↗</div></a>)}</div><a className="allWork" href="https://github.com/CodedPraveen" target="_blank" rel="noreferrer">View all projects on GitHub <span>↗</span></a></div></section>
    <section className="section shell about" id="about"><div><p className="eyebrow">A little about me</p><h2>Curious by nature.<br /><em>Reliable by choice.</em></h2></div><div className="aboutCopy"><p className="lead">I&apos;m a self-taught full-stack developer who learned the best way possible: by building, breaking, fixing, and shipping real projects.</p><p>I care about the details clients feel—speed, clarity, responsiveness, and code that can grow with the product. I communicate clearly, work consistently, and keep the project moving.</p><div className="facts"><div><strong>21+</strong><span>GitHub repositories</span></div><div><strong>Full-stack</strong><span>Frontend to backend</span></div><div><strong>India</strong><span>Available worldwide</span></div></div></div></section>
    <section className="process shell"><p className="eyebrow">How we&apos;ll work</p><div className="processGrid">{[["01","Understand","We align on the goal, audience, scope, and what success looks like."],["02","Plan","I map the pages, features, timeline, and the clearest path to launch."],["03","Build","You get steady progress, practical decisions, and a responsive product."],["04","Ship","I test, polish, launch, and make the handover easy to understand."]].map(x=><div className="step" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
    <section className="contact" id="contact"><div className="shell contactInner"><p className="eyebrow">Have a project in mind?</p><h2>Let&apos;s build something<br /><em>worth using.</em></h2><p>Tell me what you&apos;re planning. I&apos;ll reply with honest questions, a practical approach, and the next steps.</p><div className="contactActions"><a className="button lime" href="https://www.linkedin.com/in/codedpraveen" target="_blank" rel="noreferrer">Message on LinkedIn <span>↗</span></a><a className="button outline" href="https://github.com/CodedPraveen" target="_blank" rel="noreferrer">View GitHub <span>↗</span></a></div></div></section>
    <footer className="footer shell"><a className="brand" href="#top"><span>&lt;</span>codedpraveen<span>/&gt;</span></a><p>Freelance full-stack developer<br/>Jodhpur, Rajasthan, India</p><div><a href="https://github.com/CodedPraveen" target="_blank" rel="noreferrer">GitHub</a><a href="https://www.linkedin.com/in/codedpraveen" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://x.com/CodedPraveen" target="_blank" rel="noreferrer">X</a></div><small>© 2026 Praveen Kumar</small></footer>
  </main>;
}
